USER FUNCTION TESTA_IE()

pRIVATE nHdLog

nHdLog := CreateLog( "TESTE_IE.log" )

Processa({||testa_a1()}, "Testando e Corrigindo IE", "Aguarde...")

Fclose( nHdLog )
ConOut( "FIM" )

STATIC FUNCTION TESTA_A1()

ProcRegua(SA1->(Reccount()))

SA1->( DbGoTop() )                            	
DO WHILE ! SA1->( EOF() )

	iNCpROC()
	IF ! IE(SA1->A1_INSCR,SA1->A1_EST,.F.) 
		cMsg := SA1->( A1_COD + ' - ' + A1_INSCR + " - " + A1_EST + " " + A1_INAT )
		GravaLog( nHdLog, "W", cMsg )
      ConOut( cMsg )

		RECLOCK("SA1",.F.)
		A1_INSCR := " "
		MSUNLOCK()
		
  ENDIF
  
  SA1->( DBSKIP() )
  
ENDDO  

GravaLog( nHdLog, "GW" )

/*/
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณ GravaLog บ Autor ณ Felipe Raposo      บ Data ณ  20/12/07   บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑบDescricao ณ Grava no arquivo de log e exibe a mensagem no console.     บฑฑ
ฑฑบ          ณ                                                            บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
/*/
Static function GravaLog(nHandle, cTipo, cMsg)

//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ
//ณ Declaracao de variaveis.                                            ณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู
Static aWarns[0]

If cTipo == "W"  // Armazena warnings.
	aAdd(aWarns, cMsg)
ElseIf cTipo == "GW"  // Grava warnings.
	aEval(aWarns, {|cMsg| 	FWrite(nHandle, cMsg + CHR(13)+CHR(10 ) ) })
	aWarns := {}
Endif

Return .T.

Static function CreateLog(cArquivo)

//ฺฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฟ
//ณ Declaracao de variaveis.                                            ณ
//ภฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤู
Local nHandle

If (nHandle := FCreate(cArquivo)) < 1
	MsgInfo("Nใo foi possํvel criar o arquivo de log.", cArquivo)
Endif

Return nHandle
   

   
   
   
   
   
   